name: tl_flutter_openai
description: Flutter library for work with OpenAI API
homepage: https://github.com/tark/tl-flutter-openai
repository: https://github.com/tark/tl-flutter-openai
issue_tracker: https://github.com/tark/tl-flutter-openai/issues

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true