name: tl_flutter_openai
description: Flutter library for work with OpenAI API
homepage: https://github.com/tark/tl-flutter-openai
repository: https://github.com/tark/tl-flutter-openai
issue_tracker: https://github.com/tark/tl-flutter-openai/issues

version: 1.0.8+9

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: 6.9.3
  build_runner: ^2.3.3
  freezed: ^2.5.8

flutter:
  uses-material-design: true